[package]
name = "cplibs-kmp"
version = "0.1.0"
authors = ["Masooka <masooka@live.com>"]
edition = "2021"
repository = "https://github.com/masooka/cplibs"
license = "0BSD"
publish = false

[lib]
name = "kmp"
