[package]
name = "cplibs-plane"
version = "0.1.7"
authors = ["Masooka <masooka@live.com>"]
edition = "2021"
repository = "https://github.com/masooka/cplibs"
license = "0BSD"
publish = false

[lib]
name = "plane"
